### PR TITLE
Bump Pyarrow and Pandas to latest version

### PR DESCRIPTION
**Pull request by mthota15**

### CODE REVIEW

**Comment by andrewgross** [comment]
Hmm looks like the imports are breaking with the new versions.

**Comment by mthota15** [comment]
will resubmit the pull request after fixing the tests.

**Comment by andrewgross** [comment]
Poking around on this, there are some issues with how we install pyarrow.

If I install it from `setup.py` it tries to compile it, however if I just use `pip install` I have no issues.  I think the `develop` flag causes problems.  I also had to bump numpy to `1.15.0` to fix an underspecified dependency in pyarrow.  At the moment I am debugging a failing test for the output parquet file.  However, this test does a bytewise comparison of a generated file and a test file.  Unfortunately this breaks every PyArrow release since the full binary format is not stable.  I will work on revising this test.

**Comment by andrewgross** [comment]
Ok, I released `0.0.23` which uses `pyarrow==0.10.0` and also bumps pandas and numpy to the latest versions

**Pull request closed without merging**
